package com.example.catalist_android_compose.breeds.repository

import com.example.catalist_android_compose.breeds.model.Cat

val SampleData = listOf(
    Cat(
        id = "prva",
        weight = "10 lbs",
        name = "Sample Cat 1",
        temperament = "Friendly",
        origin = "Unknown",
        description = "This is a sample cat description 1.",
        lifeSpan = "10-15 years",
        indoor = 1,
        lap = 1,
        adaptability = 3,
        affectionLevels = 4,
        childFriendly = 1,
        dogFriendly = 1,
        energyLevel = 3,
        grooming = 2,
        healthIssues = 1,
        inteligence = 3,
        sheddingLevel = 2,
        socialNeeds = 3,
        strangerFriendly = 3,
        vocalisation = 2,
        experimental = 0,
        hairless = 0,
        natural = 1,
        rare = 0,
        rex = 0,
        shortLegs = 0,
        wikipediaLink = 0,
        hypoallergenic = 0,
        referenceImageId = "0XYvRd7oD",
        link = "https://example.com",
        numberOfLives = 1
    ),
    Cat(
        id = "druga",
        weight = "8 lbs",
        name = "Sample Cat 2",
        temperament = "Calm",
        origin = "Unknown",
        description = "This is a sample cat description 2.",
        lifeSpan = "12-18 years",
        indoor = 1,
        lap = 1,
        adaptability = 4,
        affectionLevels = 5,
        childFriendly = 1,
        dogFriendly = 1,
        energyLevel = 2,
        grooming = 3,
        healthIssues = 2,
        inteligence = 4,
        sheddingLevel = 3,
        socialNeeds = 4,
        strangerFriendly = 4,
        vocalisation = 1,
        experimental = 0,
        hairless = 0,
        natural = 1,
        rare = 0,
        rex = 0,
        shortLegs = 0,
        wikipediaLink = 0,
        hypoallergenic = 0,
        referenceImageId = "1ABcDefG",
        link = "https://example.com",
        numberOfLives = 1
    ),
    Cat(
        id = "treca",
        weight = "12 lbs",
        name = "Sample Cat 3",
        temperament = "Playful",
        origin = "Unknown",
        description = "This is a sample cat description 3.",
        lifeSpan = "8-12 years",
        indoor = 1,
        lap = 1,
        adaptability = 3,
        affectionLevels = 3,
        childFriendly = 1,
        dogFriendly = 1,
        energyLevel = 5,
        grooming = 1,
        healthIssues = 3,
        inteligence = 2,
        sheddingLevel = 1,
        socialNeeds = 5,
        strangerFriendly = 5,
        vocalisation = 3,
        experimental = 0,
        hairless = 0,
        natural = 1,
        rare = 0,
        rex = 0,
        shortLegs = 0,
        wikipediaLink = 0,
        hypoallergenic = 0,
        referenceImageId = "2CdeFgHi",
        link = "https://example.com",
        numberOfLives = 1
    )
)
